python:
  - "3.10"
  - "3.11"
  - "3.12"

numpy:
  - "1.26"
  - "2.0"
  - "2.1"

pin_run_as_build:
  numpy:
    max_pin: x.x

c_stdlib_version:          # [linux]
  - "2.28"                 # [linux]
